app:
  kafka:
    group-id: data-analysis-transformation-kafka

spring:
  application:
    name: data-analysis-transformation
  cloud:
    config:
      uri: http://localhost:8888
      username: dataanalysis
      password: dataanalysis
  messages:
    basename: messages/messages
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
